global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    environment: 'local'
    project: 'eventflow'

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # EventFlow Java service â€” runs on the host, not in Docker
  # host.docker.internal resolves to the host on both Mac and Linux
  # (Linux requires the extra_hosts entry in docker-compose.yml)
  - job_name: 'event-ingestion-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['host.docker.internal:8081']
    relabel_configs:
      - target_label: service
        replacement: 'event-ingestion-service'

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9101']
